spring.application.name=appointment-service

server.port=8084

spring.datasource.url=jdbc:mysql://localhost:3306/medsync
spring.datasource.username=your_username
spring.datasource.password=your_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka (if using service discovery)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Feign (if calling other services)
feign.hystrix.enabled=true
